// SRD source -> src/data/rules.json. Run at build time only — the output
// is generated and must not be hand-edited (edit data-src/ instead).
import { readFileSync, writeFileSync } from "node:fs";
import {
  RULE_GROUPS, type Flow, type QuickAction, type Rule, type RuleGroup, type SourceRecord,
} from "../src/types";

type SourceEntry = Omit<Rule, "group" | "body" | "seeAlso"> & {
  group?: RuleGroup;
  text: string;
  related: string[];
};

type RuleExtra = {
  tldr?: string;
  example?: string;
  keywords?: string[];
  actions?: QuickAction[];
};

// srd-rules-source.json is hand-authored. The rest are generated by
// scripts/import-srd-content.mjs from the 5e-bits/5e-database SRD dataset —
// re-run that importer to refresh them, don't hand-edit either kind here.
const SOURCE_PATHS = [
  "data-src/srd-rules-source.json",
  "data-src/srd-spells-source.json",
  "data-src/srd-monsters-source.json",
  "data-src/srd-magic-items-source.json",
  "data-src/srd-classes-source.json",
  "data-src/open5e-source.json",
];
const EXTRAS_PATH = "data-src/rule-extras.json";
const SOURCES_PATH = "data-src/sources.json";
const SOURCES_OUTPUT_PATH = "src/data/sources.json";
const FLOWS_PATH = "data-src/flows.json";
const OUTPUT_PATH = "src/data/rules.json";
const FLOWS_OUTPUT_PATH = "src/data/flows.json";
const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function fail(message: string): never {
  console.error(`build-rules: ${message}`);
  process.exit(1);
}

/** The hand-authored source predates groups; derive them from its categories. */
function deriveGroup(entry: SourceEntry): RuleGroup {
  if (entry.group) return entry.group;
  return entry.category === "equipment" ? "items" : "rules";
}

const source: SourceEntry[] = SOURCE_PATHS.flatMap((path) => {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as SourceEntry[];
  } catch (err) {
    fail(`could not read ${path}: ${(err as Error).message}`);
  }
});

const seenIds = new Set<string>();
for (const entry of source) {
  if (!SLUG_RE.test(entry.id)) fail(`invalid id (must be a lowercase slug): "${entry.id}"`);
  if (seenIds.has(entry.id)) fail(`duplicate id: "${entry.id}"`);
  seenIds.add(entry.id);
  if (!entry.title.trim()) fail(`missing title for id "${entry.id}"`);
  if (!entry.category.trim()) fail(`missing category for id "${entry.id}"`);
  if (!entry.text.trim()) fail(`missing body text for id "${entry.id}"`);
  const group = deriveGroup(entry);
  if (!RULE_GROUPS.includes(group)) fail(`unknown group "${group}" for id "${entry.id}"`);
}

for (const entry of source) {
  for (const relatedId of entry.related) {
    if (!seenIds.has(relatedId)) {
      fail(`"${entry.id}" has seeAlso reference to unknown id "${relatedId}"`);
    }
  }
}

// ---- hand-authored extras: TL;DRs, examples, keywords, quick actions ----
const extrasRaw = JSON.parse(readFileSync(EXTRAS_PATH, "utf8")) as Record<string, RuleExtra>;
const extras = new Map(Object.entries(extrasRaw).filter(([key]) => !key.startsWith("_")));

for (const [ruleId, extra] of extras) {
  if (!seenIds.has(ruleId)) fail(`rule-extras references unknown rule id "${ruleId}"`);
  for (const action of extra.actions ?? []) {
    if (action.kind === "rule" && !seenIds.has(action.ruleId)) {
      fail(`rule-extras "${ruleId}" has an action pointing at unknown rule "${action.ruleId}"`);
    }
  }
}

// ------------------------------------------------- decision flows -------
const flows = JSON.parse(readFileSync(FLOWS_PATH, "utf8")) as Flow[];
const flowIds = new Set<string>();

for (const flow of flows) {
  if (!SLUG_RE.test(flow.id)) fail(`invalid flow id: "${flow.id}"`);
  if (flowIds.has(flow.id)) fail(`duplicate flow id: "${flow.id}"`);
  flowIds.add(flow.id);
  if (!flow.steps.length) fail(`flow "${flow.id}" has no steps`);
  for (const step of flow.steps) {
    if (step.ruleId && !seenIds.has(step.ruleId)) {
      fail(`flow "${flow.id}" step "${step.title}" references unknown rule "${step.ruleId}"`);
    }
    for (const applied of step.applies ?? []) {
      if (!seenIds.has(applied)) {
        fail(`flow "${flow.id}" applies unknown condition "${applied}"`);
      }
    }
  }
}

for (const [ruleId, extra] of extras) {
  for (const action of extra.actions ?? []) {
    if (action.kind === "flow" && !flowIds.has(action.flowId)) {
      fail(`rule-extras "${ruleId}" has an action pointing at unknown flow "${action.flowId}"`);
    }
  }
}

const rules: Rule[] = source
  .map((entry) => {
    const { text, related, group, ...rest } = entry;
    return {
      ...rest,
      ...(extras.get(entry.id) ?? {}),
      group: deriveGroup(entry),
      body: text.trim(),
      ...(related.length ? { seeAlso: related } : {}),
    };
  })
  .sort((a, b) => a.group.localeCompare(b.group) || a.title.localeCompare(b.title));

/**
 * Packs in preference order. Black Flag and A5E are 5e-compatible reference
 * documents, so they restate most of the SRD's creatures and spells; without
 * this the bestiary listed "Eagle" twice.
 */
const PACK_PRIORITY = ["srd", "a5e", "blackflag"];

function packRank(source: string | undefined): number {
  const index = PACK_PRIORITY.indexOf(source ?? "srd");
  return index === -1 ? PACK_PRIORITY.length : index;
}

/**
 * Key for spotting the same thing under a different name. Black Flag inverts
 * its creature names ("Ape, Giant"), so the words are sorted before joining —
 * otherwise it reads as a different monster from the SRD's "Giant Ape".
 */
const titleKey = (rule: Rule) => {
  const words = rule.title
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean)
    .sort();
  return `${rule.group}::${words.join("-")}`;
};

/**
 * Drops an entry when a higher-priority pack already provides the same title
 * in the same group. Deliberately only ACROSS packs: within the SRD, several
 * entries legitimately share a name — Ability Score Improvement exists once
 * per class per level, and Extra Attack belongs to four different classes —
 * and those are told apart by their subtitles, not their titles.
 */
function dedupeAcrossPacks(all: Rule[]): { kept: Rule[]; dropped: Rule[] } {
  const bestRankByTitle = new Map<string, number>();
  for (const rule of all) {
    const key = titleKey(rule);
    const rank = packRank(rule.source);
    const seen = bestRankByTitle.get(key);
    if (seen === undefined || rank < seen) bestRankByTitle.set(key, rank);
  }

  const kept: Rule[] = [];
  const dropped: Rule[] = [];
  for (const rule of all) {
    if (packRank(rule.source) > (bestRankByTitle.get(titleKey(rule)) ?? 0)) dropped.push(rule);
    else kept.push(rule);
  }
  return { kept, dropped };
}

// Every non-SRD source must carry the notice its licence demands, or the
// entries citing it cannot ship.
const sources = JSON.parse(readFileSync(SOURCES_PATH, "utf8")) as SourceRecord[];
const sourceIds = new Set(sources.map((s) => s.id));
for (const source of sources) {
  if (!source.attribution?.trim()) fail(`source "${source.id}" has no attribution notice`);
  if (!source.license?.trim()) fail(`source "${source.id}" has no licence`);
}
for (const rule of rules) {
  if (rule.source && !sourceIds.has(rule.source)) {
    fail(`"${rule.id}" cites unknown source "${rule.source}"`);
  }
}

const { kept: deduped, dropped } = dedupeAcrossPacks(rules);

writeFileSync(OUTPUT_PATH, JSON.stringify(deduped) + "\n");
writeFileSync(FLOWS_OUTPUT_PATH, JSON.stringify(flows) + "\n");
writeFileSync(SOURCES_OUTPUT_PATH, JSON.stringify(sources) + "\n");

const counts = deduped.reduce<Record<string, number>>((acc, r) => {
  acc[r.group] = (acc[r.group] ?? 0) + 1;
  return acc;
}, {});
const explained = deduped.filter((r) => r.tldr).length;
const droppedByPack = dropped.reduce<Record<string, number>>((acc, r) => {
  const key = r.source ?? "srd";
  acc[key] = (acc[key] ?? 0) + 1;
  return acc;
}, {});
console.log(`build-rules: wrote ${deduped.length} entries to ${OUTPUT_PATH}`, counts);
if (dropped.length) {
  console.log(`build-rules: dropped ${dropped.length} cross-pack duplicates`, droppedByPack);
}
console.log(`build-rules: ${explained} entries carry a plain-English summary, ${flows.length} flows`);
