// SRD source -> src/data/rules.json. Run at build time only — the output
// is generated and must not be hand-edited (edit data-src/ instead).
import { readFileSync, writeFileSync } from "node:fs";
import { RULE_GROUPS, type Flow, type QuickAction, type Rule, type RuleGroup } from "../src/types";

type SourceEntry = Omit<Rule, "group" | "body" | "seeAlso"> & {
  group?: RuleGroup;
  text: string;
  related: string[];
};

type RuleExtra = {
  tldr?: string;
  example?: string;
  keywords?: string[];
  actions?: QuickAction[];
};

// srd-rules-source.json is hand-authored. The rest are generated by
// scripts/import-srd-content.mjs from the 5e-bits/5e-database SRD dataset —
// re-run that importer to refresh them, don't hand-edit either kind here.
const SOURCE_PATHS = [
  "data-src/srd-rules-source.json",
  "data-src/srd-spells-source.json",
  "data-src/srd-monsters-source.json",
  "data-src/srd-magic-items-source.json",
  "data-src/srd-classes-source.json",
];
const EXTRAS_PATH = "data-src/rule-extras.json";
const FLOWS_PATH = "data-src/flows.json";
const OUTPUT_PATH = "src/data/rules.json";
const FLOWS_OUTPUT_PATH = "src/data/flows.json";
const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function fail(message: string): never {
  console.error(`build-rules: ${message}`);
  process.exit(1);
}

/** The hand-authored source predates groups; derive them from its categories. */
function deriveGroup(entry: SourceEntry): RuleGroup {
  if (entry.group) return entry.group;
  return entry.category === "equipment" ? "items" : "rules";
}

const source: SourceEntry[] = SOURCE_PATHS.flatMap((path) => {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as SourceEntry[];
  } catch (err) {
    fail(`could not read ${path}: ${(err as Error).message}`);
  }
});

const seenIds = new Set<string>();
for (const entry of source) {
  if (!SLUG_RE.test(entry.id)) fail(`invalid id (must be a lowercase slug): "${entry.id}"`);
  if (seenIds.has(entry.id)) fail(`duplicate id: "${entry.id}"`);
  seenIds.add(entry.id);
  if (!entry.title.trim()) fail(`missing title for id "${entry.id}"`);
  if (!entry.category.trim()) fail(`missing category for id "${entry.id}"`);
  if (!entry.text.trim()) fail(`missing body text for id "${entry.id}"`);
  const group = deriveGroup(entry);
  if (!RULE_GROUPS.includes(group)) fail(`unknown group "${group}" for id "${entry.id}"`);
}

for (const entry of source) {
  for (const relatedId of entry.related) {
    if (!seenIds.has(relatedId)) {
      fail(`"${entry.id}" has seeAlso reference to unknown id "${relatedId}"`);
    }
  }
}

// ---- hand-authored extras: TL;DRs, examples, keywords, quick actions ----
const extrasRaw = JSON.parse(readFileSync(EXTRAS_PATH, "utf8")) as Record<string, RuleExtra>;
const extras = new Map(Object.entries(extrasRaw).filter(([key]) => !key.startsWith("_")));

for (const [ruleId, extra] of extras) {
  if (!seenIds.has(ruleId)) fail(`rule-extras references unknown rule id "${ruleId}"`);
  for (const action of extra.actions ?? []) {
    if (action.kind === "rule" && !seenIds.has(action.ruleId)) {
      fail(`rule-extras "${ruleId}" has an action pointing at unknown rule "${action.ruleId}"`);
    }
  }
}

// ------------------------------------------------- decision flows -------
const flows = JSON.parse(readFileSync(FLOWS_PATH, "utf8")) as Flow[];
const flowIds = new Set<string>();

for (const flow of flows) {
  if (!SLUG_RE.test(flow.id)) fail(`invalid flow id: "${flow.id}"`);
  if (flowIds.has(flow.id)) fail(`duplicate flow id: "${flow.id}"`);
  flowIds.add(flow.id);
  if (!flow.steps.length) fail(`flow "${flow.id}" has no steps`);
  for (const step of flow.steps) {
    if (step.ruleId && !seenIds.has(step.ruleId)) {
      fail(`flow "${flow.id}" step "${step.title}" references unknown rule "${step.ruleId}"`);
    }
    for (const applied of step.applies ?? []) {
      if (!seenIds.has(applied)) {
        fail(`flow "${flow.id}" applies unknown condition "${applied}"`);
      }
    }
  }
}

for (const [ruleId, extra] of extras) {
  for (const action of extra.actions ?? []) {
    if (action.kind === "flow" && !flowIds.has(action.flowId)) {
      fail(`rule-extras "${ruleId}" has an action pointing at unknown flow "${action.flowId}"`);
    }
  }
}

const rules: Rule[] = source
  .map((entry) => {
    const { text, related, group, ...rest } = entry;
    return {
      ...rest,
      ...(extras.get(entry.id) ?? {}),
      group: deriveGroup(entry),
      body: text.trim(),
      ...(related.length ? { seeAlso: related } : {}),
    };
  })
  .sort((a, b) => a.group.localeCompare(b.group) || a.title.localeCompare(b.title));

writeFileSync(OUTPUT_PATH, JSON.stringify(rules) + "\n");
writeFileSync(FLOWS_OUTPUT_PATH, JSON.stringify(flows) + "\n");

const counts = rules.reduce<Record<string, number>>((acc, r) => {
  acc[r.group] = (acc[r.group] ?? 0) + 1;
  return acc;
}, {});
const explained = rules.filter((r) => r.tldr).length;
console.log(`build-rules: wrote ${rules.length} entries to ${OUTPUT_PATH}`, counts);
console.log(`build-rules: ${explained} entries carry a plain-English summary, ${flows.length} flows`);
